services:
  - type: web
    name: chat-chat-service
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
      - key: DATABASE_URL
        fromDatabase:
          name: chat-database
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        value: your-cloudinary-name
      - key: CLOUDINARY_API_KEY
        value: your-cloudinary-key
      - key: CLOUDINARY_API_SECRET
        value: your-cloudinary-secret